### ISSUE TITLE
Casing important for MySQL table

### ISSUE THREAD

**Issue by koalo** [adiralashiva8/robotframework-historic#15]
The documentation https://github.com/adiralashiva8/robotframework-historic/wiki/2.2-Create-robothistoric-table explains to create a table in uppercase characters (TB_PROJECT), while the sources refer to it in lowercase characters (tb_project). This results in `MySQLdb._exceptions.ProgrammingError: (1146, "Table 'robothistoric.tb_project' doesn't exist")` on Linux hosts.

The documentation should be adapted accordingly, or even better, the program itself could create the table if it does not exist to make the initial setup easier.

**Comment by adiralashiva8** [comment]
Thank you @koalo for notifying issue, I will update document as suggested. Even I will look into possibilties of simplify setup

**Comment by koalo** [comment]
Thanks a lot for the fast response. Unfortunately I just noticed that it is even inconsistent within the sources. I will prepare a pull request for that.

**Comment by koalo** [comment]
In the pull request https://github.com/adiralashiva8/robotframework-historic/pull/16 I changed it to uppercase. So the documentation does not have to be adapted.

**Comment by adiralashiva8** [comment]
Seems this is specific to ubuntu

> In MySQL the commands themselves are not case sensitive, however depending on the OS, file structure variables might be case sensitive. 

> Check if your OS is case sensitive, and if this is the case, find out the correct case for the tables, and make sure your query is consistent in naming. Don't forget though that you'll have to rewrite a lot of the queries to make sure they work in MySQL.

Reference: https://dba.stackexchange.com/questions/64724/mysql-how-to-avoid-case-sensitivity-in-sql-queries-when-migrate-from-windows-to

I have tested in WINDOWS

**Comment by koalo** [comment]
Yes, exactly! I already noticed that you use Windows due to the screenshots in the documentation.  Therefore, I understand why you did not notice this problem. Thanks for merging!
