### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'cursor' when pushing results using rfhistoric

### ISSUE THREAD

**Issue by vikitech83** [adiralashiva8/robotframework-historic#23]

**Comment by vikitech83** [comment]
rfhistoricparser -o "output.xml" -u "superuser" -p "xxxxxxx" -n "qasmoke" -e "smoketester"
Capturing execution results, This may take few minutes...
1045 (28000): Access denied for user 'superuser'@'localhost' (using password: YES)
1045 (28000): Access denied for user 'superuser'@'localhost' (using password: YES)
Traceback (most recent call last):
  File "/usr/local/bin/rfhistoricparser", line 8, in <module>
    sys.exit(main())
  File "/home/viksingh/.local/lib/python3.8/site-packages/robotframework_historic_parser/runner.py", line 72, in main
    generate_report(args)
  File "/home/viksingh/.local/lib/python3.8/site-packages/robotframework_historic_parser/rfhistoricparser.py", line 62, in generate_report
    result_id = insert_into_execution_table(mydb, rootdb, opts.executionname, total, passed, failed, elapsedtime, stotal, spass, sfail, opts.projectname)
  File "/home/viksingh/.local/lib/python3.8/site-packages/robotframework_historic_parser/rfhistoricparser.py", line 137, in insert_into_execution_table
    cursorObj = con.cursor()
AttributeError: 'NoneType' object has no attribute 'cursor'

 mysql -u superuser -p is success.


lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal

mysql --version
mysql  Ver 8.0.21-0ubuntu0.20.04.4 for Linux on x86_64 ((Ubuntu))

**Comment by adiralashiva8** [comment]
@vikitech83 thanks for informing

Error says `authentication issue`

1045 (28000): Access denied for user 'superuser'@'localhost' (using password: YES)
1045 (28000): Access denied for user 'superuser'@'localhost' (using password: YES)

Hope you have completed these steps - https://github.com/adiralashiva8/robotframework-historic/wiki/2.1-Create-MySQL-User

I agree this setup is but tricky so could you please cross check your setup as mentioned here - https://github.com/adiralashiva8/robotframework-historic/blob/master/README.md#installation

**Comment by Ankita-020696** [comment]
> rfhistoricparser -o "output.xml" -u "superuser" -p "xxxxxxx" -n "qasmoke" -e "smoketester"
> Capturing execution results, This may take few minutes...
> 1045 (28000): Access denied for user 'superuser'@'localhost' (using password: YES)
> 1045 (28000): Access denied for user 'superuser'@'localhost' (using password: YES)
> Traceback (most recent call last):
> File "/usr/local/bin/rfhistoricparser", line 8, in
> sys.exit(main())
> File "/home/viksingh/.local/lib/python3.8/site-packages/robotframework_historic_parser/runner.py", line 72, in main
> generate_report(args)
> File "/home/viksingh/.local/lib/python3.8/site-packages/robotframework_historic_parser/rfhistoricparser.py", line 62, in generate_report
> result_id = insert_into_execution_table(mydb, rootdb, opts.executionname, total, passed, failed, elapsedtime, stotal, spass, sfail, opts.projectname)
> File "/home/viksingh/.local/lib/python3.8/site-packages/robotframework_historic_parser/rfhistoricparser.py", line 137, in insert_into_execution_table
> cursorObj = con.cursor()
> AttributeError: 'NoneType' object has no attribute 'cursor'
> 
> mysql -u superuser -p is success.
> 
> lsb_release -a
> No LSB modules are available.
> Distributor ID: Ubuntu
> Description: Ubuntu 20.04.1 LTS
> Release: 20.04
> Codename: focal
> 
> mysql --version
> mysql Ver 8.0.21-0ubuntu0.20.04.4 for Linux on x86_64 ((Ubuntu))

HI
Could you please verify password you are giving to  -p  option & password you have given while creating superuser, is it same?
rfhistoricparser -o "output.xml" -u "superuser" -p "xxxxxxx" -n "qasmoke" -e "smoketester"

Thanks

**Comment by vikitech83** [comment]
yes password is correct...I tried changing authentication handles as mysql db s hosted on ubuntu..it worked afterwards.
