### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Ankita-020696** [adiralashiva8/robotframework-historic#25]
Hi,
I am getting segmentation fault while parsing output.xml. 

**$ rfhistoricparser -o output.xml -u "superuser" -p "passw0rd" -n "test"
Capturing execution results, This may take few minutes...
Segmentation fault (core dumped)**

how do I fix this?

Thanks

**Comment by adiralashiva8** [comment]
Not sure related to robotframework-historic something with python memory issue

https://stackoverflow.com/a/10035594/6470139
