### ISSUE TITLE
Cannot show dashboardRecent properly.

### ISSUE THREAD

**Issue by JerryCCHuang** [adiralashiva8/robotframework-historic#31]
https://github.com/adiralashiva8/robotframework-historic/blob/25f46a1cd1dbb0fb78f4a697f2e138b1ef453369/robotframework_historic/app.py#L156

Hi Author,
We find out this command cannot execute in mysql db.
This is an error code
`Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'UIPSR.TB_TEST.Execution_Id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by`
![image](https://user-images.githubusercontent.com/11919070/126611588-242c1e8d-7065-4b73-804b-f321fcdc0c31.png)

But when we change to 
`cursor.execute("SELECT COUNT(*) From (SELECT Test_Name, Execution_Id From TB_TEST WHERE Test_Status='FAIL' AND Execution_Id >= %s GROUP BY Test_Name, Execution_Id HAVING COUNT(Test_Name) = 1) AS T WHERE Execution_Id=%s" % (exe_info[1][0],exe_info[0][0]))
`
It works. :)

**Comment by adiralashiva8** [comment]
Thanks alot for improvement, could you please create pull request if possible

**Comment by JerryCCHuang** [comment]
Sure, But I don't have permission.
fatal: unable to access 'https://github.com/adiralashiva8/robotframework-historic.git/': The requested URL returned error: 403

**Comment by adiralashiva8** [comment]
Following are steps to contribute:

Step 1: Fork the repository
Step 2: clone the forked repo to local
Step 3: make required changes and push the code
Step 4: create pull request where destination is (my project,  not forked
one)

Please have a try and do let me know if you need any help

**Comment by JerryCCHuang** [comment]
Done.

**Comment by adiralashiva8** [comment]
Fixed in PR - https://github.com/adiralashiva8/robotframework-historic/pull/32
